package com.adarsh.hellomom.domain.repository

import com.adarsh.hellomom.data.local.entity.ReminderEntity
import com.adarsh.hellomom.data.local.entity.ReminderStatus
import kotlinx.coroutines.flow.Flow

interface ReminderRepository {
    fun getAllReminders(): Flow<List<ReminderEntity>>
    suspend fun getReminderById(id: Int): ReminderEntity?
    suspend fun insertReminder(reminder: ReminderEntity): Long
    suspend fun updateReminder(reminder: ReminderEntity)
    suspend fun deleteReminder(reminder: ReminderEntity)
    suspend fun syncReminders(): Result<Unit>
    suspend fun getRemindersByStatus(status: ReminderStatus): Flow<List<ReminderEntity>>
    suspend fun markAsDone(id: Int)
    suspend fun snooze(id: Int, customTimeMillis: Long? = null)
    suspend fun markAsMissed(id: Int)
    suspend fun getExistingReminder(userId: String, title: String, date: String, time: Long): ReminderEntity?
    suspend fun deleteOldReminders(expiryTime: Long)
    suspend fun getAutoGeneratedRemindersForDate(date: String): List<ReminderEntity>
}
