package com.adarsh.hellomom.domain.repository

import com.adarsh.hellomom.data.local.entity.ReminderEntity
import com.adarsh.hellomom.data.local.entity.ReminderStatus
import kotlinx.coroutines.flow.Flow

interface ReminderRepository {
    fun getAllReminders(): Flow<List<ReminderEntity>>
    suspend fun getReminderById(id: Int): ReminderEntity?
    suspend fun insertReminder(reminder: ReminderEntity): Long
    suspend fun updateReminder(reminder: ReminderEntity)
    suspend fun deleteReminder(reminder: ReminderEntity)
    suspend fun syncReminders(): Result<Unit>
    suspend fun getRemindersByStatus(status: ReminderStatus): Flow<List<ReminderEntity>>
    suspend fun markAsDone(id: Int)
    suspend fun snooze(id: Int, customTimeMillis: Long? = null)
    suspend fun markAsMissed(id: Int)
    suspend fun getExistingReminder(userId: String, title: String, date: String, time: Long): ReminderEntity?
    /**
     * Purge reminders whose time is before [expiryTime] from Room. When [deleteRemote] is true
     * (owner only), the same rows are also removed from Firestore so storage stays bounded and
     * other family devices drop them on their next pull. Appointments are a separate entity and
     * are never affected by this.
     */
    suspend fun deleteOldReminders(expiryTime: Long, deleteRemote: Boolean = false)
    suspend fun getAutoGeneratedRemindersForDate(date: String): List<ReminderEntity>
}
