package com.adarsh.hellomom.domain.repository

import com.adarsh.hellomom.data.local.entity.ReminderEntity
import kotlinx.coroutines.flow.Flow

interface ReminderRepository {
    fun getAllReminders(): Flow<List<ReminderEntity>>
    suspend fun getReminderById(id: Int): ReminderEntity?
    suspend fun insertReminder(reminder: ReminderEntity): Long
    suspend fun updateReminder(reminder: ReminderEntity)
    suspend fun deleteReminder(reminder: ReminderEntity)
    suspend fun syncReminders(): Result<Unit>
    suspend fun markAsDone(id: Int)
    suspend fun snooze(id: Int, customTimeMillis: Long? = null)
    suspend fun markAsMissed(id: Int)
    suspend fun getExistingReminder(userId: String, title: String, date: String, time: Long): ReminderEntity?
    /**
     * Purge reminders whose time is before [expiryTime] from Room. When [deleteRemote] is true
     * (owner only), the same rows are also removed from Firestore so storage stays bounded and
     * other family devices drop them on their next pull. Appointments are a separate entity and
     * are never affected by this.
     */
    suspend fun deleteOldReminders(expiryTime: Long, deleteRemote: Boolean = false)
    suspend fun getAutoGeneratedRemindersForDate(date: String): List<ReminderEntity>

    /**
     * Ensure today's fixed set of daily auto-reminders exists for [userId]. Idempotent: titles
     * already present for today are skipped, so it is safe to call repeatedly (on launch, on every
     * background sync, at midnight). Each newly created reminder is persisted to Room, pushed to
     * Firestore, and — when its time is still in the future — armed as a local alarm so the
     * notification fires. Only the owner (the single writer) should call this; family members
     * receive the reminders via the normal pull/sync. Returns the reminders created this call.
     */
    suspend fun ensureDailyReminders(userId: String, userName: String): List<ReminderEntity>

    /**
     * One-time, idempotent cleanup of genuine duplicate reminders for [userId] — rows sharing the
     * same title + date + fire-time but with different ids (left behind by the old daily-generation
     * bug). Keeps the freshest copy of each, deletes the rest from Room and (when [deleteRemote] is
     * true — owner only) from Firestore, and cancels the deleted rows' alarms. Returns how many
     * duplicates were removed. Safe to call repeatedly; a no-op once the data is clean.
     */
    suspend fun purgeDuplicateReminders(userId: String, deleteRemote: Boolean = false): Int

    /**
     * Day-change cleanup. Any reminder that was due before [startOfDayMillis] (on a previous day)
     * and that the user never acted on — still PENDING or SNOOZED — is marked EXPIRED and synced,
     * so it shows as missed in Reminder Logs. Reminders due today or later are left untouched.
     * Returns the affected reminder ids so the caller can dismiss their lingering notifications.
     */
    suspend fun expireStalePendingBefore(startOfDayMillis: Long): List<Int>
}
