package com.adarsh.hellomom.core.utils

import com.adarsh.hellomom.data.local.entity.ReminderEntity
import com.adarsh.hellomom.data.local.entity.ReminderType

/**
 * Collapses duplicate reminders for display / scheduling.
 *
 * Daily auto-reminders ([ReminderType.PREDEFINED]) are keyed by **user + title + date** — so the
 * SAME daily reminder shows exactly once even after it's snoozed to a new time (which changes its
 * `time`/status), and any legacy duplicate rows from the old generator collapse too. Custom
 * reminders are keyed by id (each is intentionally distinct — two "Drink water" reminders at
 * different times must both survive). The freshest copy (highest `updatedAt`) of each group wins,
 * so the latest status (SNOOZED / COMPLETED / EXPIRED) is the one shown.
 *
 * Note: keyed on [ReminderEntity.reminderType] (a reliable enum) NOT `isAutoGenerated`, because the
 * latter is an `is`-prefixed boolean that doesn't round-trip through Firestore (see PROJECT_GUIDE §4).
 */
object ReminderDedup {
    fun dedupe(reminders: List<ReminderEntity>): List<ReminderEntity> =
        reminders
            .groupBy { r ->
                if (r.reminderType == ReminderType.PREDEFINED) "auto|${r.userId}|${r.title}|${r.date}"
                else "id|${r.id}"
            }
            .map { (_, copies) -> copies.maxByOrNull { it.updatedAt }!! }
}
