package com.adarsh.hellomom.data.local.dao

import androidx.room.*
import com.adarsh.hellomom.data.local.entity.ReminderEntity
import com.adarsh.hellomom.data.local.entity.ReminderStatus
import kotlinx.coroutines.flow.Flow

@Dao
interface ReminderDao {
    @Query("SELECT * FROM reminders ORDER BY time ASC")
    fun getAllReminders(): Flow<List<ReminderEntity>>

    @Query("SELECT * FROM reminders WHERE id = :id")
    suspend fun getReminderById(id: Int): ReminderEntity?

    @Query("SELECT * FROM reminders WHERE status = :status")
    fun getRemindersByStatus(status: ReminderStatus): Flow<List<ReminderEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertReminder(reminder: ReminderEntity): Long

    @Update
    suspend fun updateReminder(reminder: ReminderEntity)

    @Delete
    suspend fun deleteReminder(reminder: ReminderEntity)

    @Query("SELECT * FROM reminders WHERE synced = 0")
    suspend fun getUnsyncedReminders(): List<ReminderEntity>

    @Query("SELECT * FROM reminders WHERE time <= :currentTime AND status = 'PENDING'")
    suspend fun getPendingRemindersBefore(currentTime: Long): List<ReminderEntity>

    @Query("SELECT COUNT(*) FROM reminders WHERE status = 'PENDING' AND time <= :currentTime")
    suspend fun getActiveNotificationCount(currentTime: Long): Int

    @Query("SELECT * FROM reminders WHERE userId = :userId AND title = :title AND date = :date AND time = :time LIMIT 1")
    suspend fun getExistingReminder(userId: String, title: String, date: String, time: Long): ReminderEntity?

    @Query("DELETE FROM reminders WHERE time < :expiryTime")
    suspend fun deleteOldReminders(expiryTime: Long)

    @Query("SELECT * FROM reminders WHERE date = :date AND isAutoGenerated = 1")
    suspend fun getAutoGeneratedRemindersForDate(date: String): List<ReminderEntity>

    // Reconciliation after a pull: synced rows missing remotely were deleted on another device.
    // Unsynced rows (synced = 0) are local creations that haven't been pushed yet — keep them.
    @Query("SELECT * FROM reminders WHERE userId = :userId AND synced = 1 AND id NOT IN (:keepIds)")
    suspend fun getStaleReminders(userId: String, keepIds: List<Int>): List<ReminderEntity>

    @Query("DELETE FROM reminders WHERE userId = :userId AND synced = 1 AND id NOT IN (:keepIds)")
    suspend fun deleteRemindersNotIn(userId: String, keepIds: List<Int>)
}
