package com.adarsh.hellomom.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "reminders")
data class ReminderEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String = "",
    val description: String = "",
    val voiceMessage: String = "",
    val time: Long = 0,
    val date: String = "", // Format: YYYY-MM-DD
    val status: ReminderStatus = ReminderStatus.PENDING,
    val userId: String = "",
    val userName: String = "",
    val category: String = "Custom",
    val reminderType: ReminderType = ReminderType.CUSTOM,
    val isAutoGenerated: Boolean = false,
    val lastTriggeredTime: Long? = null,
    val completedTime: Long? = null,
    val snoozedUntil: Long? = null,
    val snoozeCount: Int = 0,
    val synced: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

enum class ReminderStatus {
    PENDING, COMPLETED, EXPIRED, SNOOZED
}

enum class ReminderType {
    PREDEFINED, CUSTOM
}
